[auth]
username = "egi0397"
password = "Keiler1@@1"

[supabase]
SUPABASE_URL = "https://wqkmdfgklgiczdqptidb.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indxa21kZmdrbGdpY3pkcXB0aWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTEyNzgsImV4cCI6MjA1OTQyNzI3OH0.kHivXh-aErNsO-ktxwYf4hPl8Cl6leDNwGWzqG7xQ-g"
